name: React App CD

on:
  workflow_run:
    workflows: React App CI
    branches: main
    types: completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
        
    - name: Deploy
      run: |
        npm ci
        npm run deploy --if-present
